"""A tiny, self-contained opening book: a hash-keyed table of preferred
replies plus a single lookup function (architecture.md §15, Milestone 5).

Per the module-boundary DAG (architecture.md §11), `book.py` sits at the
same layer as `search.py`/`uci.py`: it depends on `board.py` and
`movegen.py` (to decode a UCI move string into this engine's own packed
move encoding via `movegen.move_from_uci`), and nothing below those two in
the DAG ever imports `book.py`, so this creates no cycle. `book.py` does
not import `search.py` and `search.py` does not import `book.py` — the
book is consulted only *before* the main search runs (by whatever caller,
e.g. the UCI layer, chooses to consult it) and has zero effect on
`Search.search`'s contract, exactly as §15 specifies.

**Format.** `OPENING_BOOK` is keyed by a position's Zobrist hash
(architecture.md §7 — the very same incrementally-maintained
`board.zobrist_hash`, not a separately-computed key) and maps to a list of
`(uci_move, weight)` pairs for that position: higher `weight` is more
preferred, and ties are broken by list order (first-listed wins), so
`probe_book` is fully deterministic and reproducible/testable.

**How the table below was produced.** Every key in `OPENING_BOOK` is the
*actual* `board.zobrist_hash` this engine computes for that position — not
a hand-computed or transcribed value. It was generated by a one-off script
that built a real `Board` via `Board.starting_position()`, replayed each
opening line's moves with `movegen.move_from_uci` + `board.make_move`, and
read `board.zobrist_hash` at every branching position, then printed the
resulting dict literal pasted in below. Since `zobrist.py` seeds its RNG
with a fixed constant (`random.Random(0xC0FFEE)`, see zobrist.py), these
keys are stable across runs/processes for this codebase, exactly like the
`board.zobrist_hash == compute_hash(board)` invariant `test_zobrist.py`
already relies on. The generation script (kept out of the package,
reproduced here for anyone who wants to regenerate or extend the table):

    import sys
    sys.path.insert(0, "src")
    from chessengine.board import Board
    from chessengine.movegen import move_from_uci

    # TREE: uci_move -> (weight, label, child_tree_or_None)
    TREE = { ... }  # the repertoire, see below for the one actually used

    entries = {}

    def walk(board, tree, path):
        entries[board.zobrist_hash] = [
            (uci, weight) for uci, (weight, _label, _child) in tree.items()
        ]
        for uci, (_weight, _label, child) in tree.items():
            m = move_from_uci(board, uci)
            board.make_move(m)
            if child:
                walk(board, child, path + [uci])
            board.unmake_move()

    root = Board.starting_position()
    walk(root, TREE, [])

**Repertoire covered** (a demonstration book, not a database): after 1.e4 —
...e5 (Ruy Lopez / Italian / Petrov branches), ...c5 (Sicilian: Najdorf /
Open / Rossolimo), ...e6 (French: Classical / Tarrasch), ...c6 (Caro-Kann:
Classical / Advance); after 1.d4 — ...d5 (Queen's Gambit: QGD / Slav /
QGA), ...Nf6 (Indian: King's Indian / Nimzo-QID setups); plus 1.Nf3 (Reti)
and 1.c4 (English) as alternate first moves, each with a short reply tree.
"""

from __future__ import annotations

from .board import Board
from .movegen import move_from_uci

# Keyed by `board.zobrist_hash`; each value is [(uci_move, weight), ...] for
# that position, highest weight most preferred, ties broken by list order.
OPENING_BOOK: dict[int, list[tuple[str, int]]] = {
    15362853024033725156: [  # after (startpos)
        ("e2e4", 10),  # 1.e4
        ("d2d4", 9),  # 1.d4
        ("g1f3", 5),  # 1.Nf3 (Reti Opening)
        ("c2c4", 5),  # 1.c4 (English Opening)
    ],
    6631199872573078932: [  # after 1.e4
        ("e7e5", 10),  # 1...e5 (Open Game)
        ("c7c5", 9),  # 1...c5 (Sicilian Defense)
        ("e7e6", 6),  # 1...e6 (French Defense)
        ("c7c6", 5),  # 1...c6 (Caro-Kann Defense)
    ],
    13689547676717109626: [  # after 1.e4 e5
        ("g1f3", 10),  # 2.Nf3
        ("f1c4", 4),  # 2.Bc4 (Bishop's Opening)
    ],
    10356298366559046060: [  # after 1.e4 e5 2.Nf3
        ("b8c6", 10),  # 2...Nc6
        ("g8f6", 6),  # 2...Nf6 (Petrov Defense)
    ],
    10988314749691061306: [  # after 1.e4 e5 2.Nf3 Nc6
        ("f1b5", 10),  # 3.Bb5 (Ruy Lopez)
        ("f1c4", 8),  # 3.Bc4 (Italian Game)
    ],
    11345898430574160494: [  # after 1.e4 e5 2.Nf3 Nf6
        ("f3e5", 6),  # 3.Nxe5
        ("b1c3", 6),  # 3.Nc3
    ],
    15775764521182090959: [  # after 1.e4 e5 2.Bc4
        ("g8f6", 8),  # 2...Nf6
        ("f8c5", 6),  # 2...Bc5
    ],
    6806165760902825634: [  # after 1.e4 c5
        ("g1f3", 10),  # 2.Nf3
        ("b1c3", 4),  # 2.Nc3
    ],
    3384541420687667921: [  # after 1.e4 c5 2.Nf3
        ("d7d6", 9),  # 2...d6 (Najdorf setup)
        ("b8c6", 8),  # 2...Nc6 (Open Sicilian)
        ("e7e6", 6),  # 2...e6 (Taimanov/Kan setup)
    ],
    3986307452363715476: [  # after 1.e4 c5 2.Nf3 d6
        ("d2d4", 10),  # 3.d4
    ],
    4124996027560206151: [  # after 1.e4 c5 2.Nf3 Nc6
        ("d2d4", 8),  # 3.d4
        ("f1b5", 6),  # 3.Bb5 (Rossolimo)
    ],
    18290712421202613077: [  # after 1.e4 c5 2.Nc3
        ("b8c6", 7),  # 2...Nc6
    ],
    3590468057890429458: [  # after 1.e4 e6
        ("d2d4", 10),  # 2.d4
    ],
    10068049174337606516: [  # after 1.e4 e6 2.d4
        ("d7d5", 10),  # 2...d5
    ],
    1466286858252639712: [  # after 1.e4 e6 2.d4 d5
        ("b1c3", 8),  # 3.Nc3 (Classical French)
        ("b1d2", 6),  # 3.Nd2 (Tarrasch)
    ],
    3543045951446797296: [  # after 1.e4 c6
        ("d2d4", 10),  # 2.d4
    ],
    10034142325491597974: [  # after 1.e4 c6 2.d4
        ("d7d5", 10),  # 2...d5
    ],
    1486687095271820290: [  # after 1.e4 c6 2.d4 d5
        ("b1c3", 8),  # 3.Nc3 (Classical Caro-Kann)
        ("e4e5", 7),  # 3.e5 (Advance Variation)
    ],
    8023395422530442114: [  # after 1.d4
        ("d7d5", 10),  # 1...d5
        ("g8f6", 9),  # 1...Nf6 (Indian Defenses)
        ("e7e6", 4),  # 1...e6
    ],
    17346030550356991254: [  # after 1.d4 d5
        ("c2c4", 10),  # 2.c4 (Queen's Gambit)
        ("g1f3", 6),  # 2.Nf3
    ],
    1793094403735832943: [  # after 1.d4 d5 2.c4
        ("e7e6", 9),  # 2...e6 (QGD)
        ("c7c6", 8),  # 2...c6 (Slav)
        ("d5c4", 5),  # 2...dxc4 (QGA)
    ],
    16982256187560333928: [  # after 1.d4 Nf6
        ("c2c4", 10),  # 2.c4
        ("g1f3", 6),  # 2.Nf3
    ],
    10795053959323149369: [  # after 1.d4 Nf6 2.c4
        ("g7g6", 8),  # 2...g6 (King's Indian setup)
        ("e7e6", 7),  # 2...e6 (Nimzo/Queen's Indian setup)
    ],
    18017448596681166002: [  # after 1.d4 e6
        ("c2c4", 8),  # 2.c4
        ("g1f3", 6),  # 2.Nf3
    ],
    9930024303363627180: [  # after 1.Nf3
        ("d7d5", 7),  # 1...d5
        ("g8f6", 7),  # 1...Nf6
    ],
    9229747442678608912: [  # after 1.Nf3 d5
        ("g2g3", 7),  # 2.g3 (Kings Indian Attack setup)
        ("d2d4", 6),  # 2.d4 (transposing)
    ],
    11169706092454296430: [  # after 1.Nf3 Nf6
        ("c2c4", 7),  # 2.c4 (transposing to English/Reti)
        ("g2g3", 5),  # 2.g3
    ],
    12344776741733477557: [  # after 1.c4
        ("e7e5", 6),  # 1...e5 (Reversed Sicilian)
        ("g8f6", 6),  # 1...Nf6
        ("c7c5", 5),  # 1...c5 (Symmetrical English)
    ],
    604423107318557950: [  # after 1.c4 e5
        ("b1c3", 7),  # 2.Nc3
    ],
    10803138429545871692: [  # after 1.c4 Nf6
        ("b1c3", 7),  # 2.Nc3
    ],
    16999970643782400806: [  # after 1.c4 c5
        ("g1f3", 6),  # 2.Nf3
    ],
}


def probe_book(board: Board) -> int | None:
    """Look up `board`'s current position in `OPENING_BOOK` and return the
    engine's own encoded move (architecture.md §4) for the single
    highest-weight entry, or `None` if the position isn't in the book.

    Deterministic: ties are broken by first-listed entry (§15), so this is
    reproducible/testable without relying on dict ordering guarantees beyond
    what `OPENING_BOOK`'s own list order already provides. Decodes via
    `movegen.move_from_uci` against the *current* legal move list, so it can
    never hand back a move the position's own generator wouldn't produce —
    the same safety property `move_from_uci` gives UCI's `position ... moves
    ...` handling.

    Standalone: never imports or calls anything in `search.py`, and nothing
    in `search.py` calls this — consulting it (or not) before `Search.search`
    runs is entirely up to the caller (the UCI layer, in a later phase).
    """
    moves = OPENING_BOOK.get(board.zobrist_hash)
    if not moves:
        return None
    best_uci, _best_weight = max(
        enumerate(moves), key=lambda pair: (pair[1][1], -pair[0])
    )[1]
    return move_from_uci(board, best_uci)
